### PR TITLE
Update README.md and index.html

### LINKED ISSUE #31: Improve Readme
- [x]  Add the Game Rules and workflow(as seen by the player). 
- [x] Add a GIF for the working of Game,

The app is purely static, so can easily be cloned and used. :)

### PR DESCRIPTION
**Pull request by swapniljha001**
- [x] Added `Rules of Gameplay` in `README.md`
- [x] Fixes #31
- [x] Improved the grammar in `index.html`.

### CODE REVIEW

**Comment by Apoorve73** [comment]
I really appreciate your work! Can you please pull the changes from the pull requests of Restyled bot and push again. This will help you to clear all the test cases by the bot! Then You are Good to go! :)

**Comment by swapniljha001** [comment]
@Apoorve73, done, thankfully, it was a single whitespace error, :)

**Comment by Apoorve73** [comment]
Great! Would you like to add a GIF of Game's working?
Or I will merge the PR, else will set it to WIP.

**Comment by swapniljha001** [comment]
I'm not sure how to capture a gif 😅, so it would be preferable if it is set as WIP, so that others can add the gif.

**Comment by Apoorve73** [comment]
Cool! No worries!

**Pull request merged**
